homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  customize: !include_dir_merge_named customization

recorder:
  purge_interval: 1
  purge_keep_days: 7
  exclude:
#    domains:
#      - automation
    entities:
      - sun.sun   # Don't record sun data

## Features ##
# Enables the frontend
frontend:
# Checks for available updates
#updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:

history_graph: !include history_graph.yaml
# View all events in a logbook
logbook:
# Track the sun
sun:
# Enables Amazon Echo / Hue functions:
emulated_hue:
  expose_by_default: false
    
tradfri:
  host: !secret tradfri_ip
 
## Cloud
cloud:
## Amazon Echo
alexa: !include alexa.yaml
## Groups ##
group: !include groups.yaml
## HTTP ##
http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
## DuckDNS ##
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

## No-IP ##
no_ip:
  domain: !secret no-ip_domain
  username: !secret no-ip_username
  password: !secret no-ip_password

# Google
google:
  client_id: 109191048287-9gn8tmn86c9ha2538s4opm8peut1teob.apps.googleusercontent.com
  client_secret: ozWdinh5ng29vHxG4QHwUlgs
  
# Sensor
sensor: !include sensor.yaml

## Scripts ##
script: !include scripts.yaml
## Scenes ##
scene: !include_dir_merge_list scenes
## Automation ##
automation: !include_dir_merge_list automation
## Inputs ##
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
binary_sensor: !include binary_sensors.yaml

## Cover ##
cover: !include cover.yaml

## Panels ##
panel_custom: !include panel_custom.yaml

## Configurations ##
config:

## Map Panel ##
map:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key
  autoheal: false
#  polling_interval: 60000

zha:
  usb_path: /dev/zigbee
  database_path: /home/homeassistant/.homeassistant/zigbee.db

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_ids

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids: !secret telegram_ids
    
# vacuum:
  # platform: roomba
  # name: Roomba
  
  
  # host: !secret roomba_ip
  # username: !secret roomba_username
  # password: !secret roomba_password

# Text to speech
tts:
  platform: google

device_tracker:
  - platform: owntracks
  - platform: bluetooth_tracker
    device_id: hci0
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  # - platform: asuswrt
    # host: !secret asus_host
    # username: !secret asus_username
    # password: !secret asus_password
    # protocol: telnet
    # interval_seconds: 15
    # consider_home: 0:10:00
  - platform: google_maps
    consider_home: 0:10:00
    username: !secret google-map-user
    password: !secret google-map-pass

mqtt:
  broker: !secret no-ip_domain
  # broker: m13.cloudmqtt.com
  # port: 14579
  # client_id: !secret mqtt_client_id
  # keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  # customize: true

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:home

zone 2:
  name: Tyler's Work
  latitude: !secret tylers_work_latitude
  longitude: !secret tylers_work_longitude
  radius: 250
  icon: mdi:worker

zone 3:
  name: Elementry School
  latitude: !secret saywer_school_latitude
  longitude: !secret saywer_school_longitude
  radius: 250
  icon: mdi:school

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

light: !include light.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt

media_player:
  - platform: sonos

shell_command:
  ssl_renew: ~/certbot renew --standalone --preferred-challenges http-01