homeassistant:
  name: Home
  unit_system: imperial
  time_zone: America/Los_Angeles
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  customize: !include_dir_merge_named customization

recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
#    domains:
#      - automation
    entities:
      - sun.sun   # Don't record sun data

## Features ##
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
# Checks for available updates
#updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:

## Configurations ##
config:

## Map Panel ##
# map:
system_health:

tts:
  - platform: google_translate

history_graph: !include history_graph.yaml
# View all events in a logbook
logbook:
# Track the sun
sun:
# Enables Amazon Echo / Hue functions:
emulated_hue:
  expose_by_default: false
    
tradfri:
  host: !secret tradfri_ip
  allow_tradfri_groups: true
## Cloud
cloud:
## Amazon Echo
alexa: !include alexa.yaml
## Groups ##
group: !include groups.yaml
## HTTP ##
http:
  #api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
## DuckDNS ##
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

## No-IP ##
no_ip:
  domain: !secret no-ip_domain
  username: !secret no-ip_username
  password: !secret no-ip_password

# Google
google:
  client_id: 109191048287-9gn8tmn86c9ha2538s4opm8peut1teob.apps.googleusercontent.com
  client_secret: ozWdinh5ng29vHxG4QHwUlgs
  
# Sensor
sensor: !include sensor.yaml

## Scripts ##
script: !include scripts.yaml
## Scenes ##
scene: !include_dir_merge_list scenes
## Automation ##
automation: !include_dir_merge_list automation
## Inputs ##
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml

binary_sensor: !include binary_sensors.yaml

## Cover ##
cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key
  autoheal: false
#  polling_interval: 60000

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_ids

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids: !secret telegram_ids
    
# vacuum:
  # platform: roomba
  # name: Roomba
  
  
  # host: !secret roomba_ip
  # username: !secret roomba_username
  # password: !secret roomba_password

person: !include people.yaml

device_tracker:
  - platform: bluetooth_le_tracker
  - platform: bluetooth_tracker
    request_rssi: true
  - platform: google_maps
    username: !secret google-map-user
    password: !secret google-map-pass

mqtt:
  broker: !secret no-ip_domain
  # broker: m13.cloudmqtt.com
  # port: 14579
  # client_id: !secret mqtt_client_id
  # keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  # customize: true

zone:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 50
  icon: mdi:home

zone 2:
  name: Tyler's Work
  latitude: !secret tylers_work_latitude
  longitude: !secret tylers_work_longitude
  radius: 250
  icon: mdi:worker

zone 3:
  name: Elementry School
  latitude: !secret saywer_school_latitude
  longitude: !secret saywer_school_longitude
  radius: 250
  icon: mdi:school

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

light: !include light.yaml

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

ifttt:
  key: !secret ifttt
  
sabnzbd:
  api_key: !secret sabnzbd_api
  host: 192.168.1.5
  name: !secret sabnzbd_user
  port: 9090
  ssl: true
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size  

shell_command:
  ssl_renew: ~/certbot renew --standalone --preferred-challenges http-01
  
###### IP Cameras
ffmpeg:
 
camera:
  - platform: ffmpeg
    name: Garage Cam
    input: !secret garage_cam_url
  - platform: ffmpeg
    name: Front1
    input: !secret front1_cam_url

plant: !include plant.yaml

sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password

# withings:
  # client_id: !secret withings_CLIENT_ID
  # client_secret: !secret withings_CLIENT_SECRET
  # profiles:
    # - Tyler