autoheal: false
binary_sensor.motion_masterbedroom_sensor_15_0:
  ignored: false
  polling_intensity: 0
binary_sensor.motion_upstairs_sensor_7_0:
  ignored: false
  polling_intensity: 1
binary_sensor.motion_entryway_sensor_5_0:
  ignored: false
  polling_intensity: 1
sensor.motion_masterbedroom_sourcenodeid_15_2:
  ignored: true
  polling_intensity: 1
sensor.watersensor_alarm_type_14_0:
  ignored: true
  polling_intensity: 1
